In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("results.csv")

In [5]:
data

,event,phase,mode,fault_model,group_id,fault_count,pool_index_0,pool_index_1,pool_index_2,image_id,label,pred_class,top1_prob,golden_pred_class,golden_top1_prob,status,injection_status
0,result,golden,golden,none,NaN,NaN,NaN,NaN,NaN,0,9,9,0.996094,NaN,NaN,ok,none
1,result,golden,golden,none,NaN,NaN,NaN,NaN,NaN,1,7,7,0.996094,NaN,NaN,ok,none
2,result,golden,golden,none,NaN,NaN,NaN,NaN,NaN,2,6,6,0.996094,NaN,NaN,ok,none
3,result,golden,golden,none,NaN,NaN,NaN,NaN,NaN,3,2,2,0.996094,NaN,NaN,ok,none
4,result,golden,golden,none,NaN,NaN,NaN,NaN,NaN,4,2,2,0.996094,NaN,NaN,ok,none
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100095,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,95,7,7,0.996094,7.0,0.996094,ok,injected
100096,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,96,2,2,0.996094,2.0,0.996094,ok,injected
100097,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,97,3,3,0.996094,3.0,0.996094,ok,injected
100098,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,98,2,2,0.996094,2.0,0.996094,ok,injected
100099,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,99,8,8,0.996094,8.0,0.996094,ok,injected

In [7]:
class2 = pd.read_csv("classified_results.csv")

In [8]:
class2

,event,phase,mode,fault_model,group_id,fault_count,pool_index_0,pool_index_1,pool_index_2,image_id,label,pred_class,top1_prob,golden_pred_class,golden_top1_prob,status,injection_status,golden_pred_class_ref,golden_top1_prob_ref,fault_class
0,result,fault,multi_fault,memory,0.0,3.0,161.0,1185.0,1400.0,0,9,9,0.996094,9.0,0.996094,ok,injected,9,0.996094,Masked
1,result,fault,multi_fault,memory,0.0,3.0,161.0,1185.0,1400.0,1,7,7,0.996094,7.0,0.996094,ok,injected,7,0.996094,Masked
2,result,fault,multi_fault,memory,0.0,3.0,161.0,1185.0,1400.0,2,6,6,0.996094,6.0,0.996094,ok,injected,6,0.996094,Masked
3,result,fault,multi_fault,memory,0.0,3.0,161.0,1185.0,1400.0,3,2,2,0.996094,2.0,0.996094,ok,injected,2,0.996094,Masked
4,result,fault,multi_fault,memory,0.0,3.0,161.0,1185.0,1400.0,4,2,2,0.996094,2.0,0.996094,ok,injected,2,0.996094,Masked
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,95,7,7,0.996094,7.0,0.996094,ok,injected,7,0.996094,Masked
99996,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,96,2,2,0.996094,2.0,0.996094,ok,injected,2,0.996094,Masked
99997,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,97,3,3,0.996094,3.0,0.996094,ok,injected,3,0.996094,Masked
99998,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,98,2,2,0.996094,2.0,0.996094,ok,injected,2,0.996094,Masked
99999,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,99,8,8,0.996094,8.0,0.996094,ok,injected,8,0.996094,Masked

In [18]:
class2['fault_class'].value_counts()

fault_class
Masked        93369
Critical       3479
Acceptable     2561
Warning         591
Name: count, dtype: int64

In [20]:
class3 = pd.read_csv("/Downloads/framework_jose/runs/multi_memoryfi_lenet5_mnist_20260414_091416/classified_results.csv")

In [17]:
class3

,event,phase,mode,fault_model,group_id,fault_count,pool_index_0,pool_index_1,pool_index_2,image_id,label,pred_class,top1_prob,golden_pred_class,golden_top1_prob,status,injection_status,golden_pred_class_ref,golden_top1_prob_ref,fault_class
0,result,fault,multi_fault,memory,0.0,3.0,161.0,1185.0,1400.0,0,9,9,0.996094,9.0,0.996094,ok,injected,9,0.996094,Masked
1,result,fault,multi_fault,memory,0.0,3.0,161.0,1185.0,1400.0,1,7,7,0.996094,7.0,0.996094,ok,injected,7,0.996094,Masked
2,result,fault,multi_fault,memory,0.0,3.0,161.0,1185.0,1400.0,2,6,6,0.996094,6.0,0.996094,ok,injected,6,0.996094,Masked
3,result,fault,multi_fault,memory,0.0,3.0,161.0,1185.0,1400.0,3,2,2,0.996094,2.0,0.996094,ok,injected,2,0.996094,Masked
4,result,fault,multi_fault,memory,0.0,3.0,161.0,1185.0,1400.0,4,2,2,0.996094,2.0,0.996094,ok,injected,2,0.996094,Masked
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,95,7,7,0.996094,7.0,0.996094,ok,injected,7,0.996094,Masked
99996,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,96,2,2,0.996094,2.0,0.996094,ok,injected,2,0.996094,Masked
99997,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,97,3,3,0.996094,3.0,0.996094,ok,injected,3,0.996094,Masked
99998,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,98,2,2,0.996094,2.0,0.996094,ok,injected,2,0.996094,Masked
99999,result,fault,multi_fault,memory,999.0,3.0,61.0,357.0,1136.0,99,8,8,0.996094,8.0,0.996094,ok,injected,8,0.996094,Masked

In [19]:
class3['fault_class'].value_counts()

fault_class
Masked        93369
Critical       3479
Acceptable     2561
Warning         591
Name: count, dtype: int64